"""Travel Places Discovery Service — Provides curated stays, food, and attractions along travel corridors."""
from __future__ import annotations

from typing import Any


class TravelPlacesService:
    def get_corridor_places(self, checkpoint_id: str | None = None, category: str | None = None) -> list[dict[str, Any]]:
        places = [
            # ── Stays ──
            {
                "checkpoint_id": "cp-02",
                "category": "stay",
                "name": "Quality Hotel Dvas",
                "address": "MG Road, Vijayawada",
                "lat": 16.508,
                "lng": 80.64,
                "description": "Highway-accessible hotel with secure parking and buffet breakfast",
                "rating": 4.3,
                "review_count": 310,
                "price_min": 1750.0,
                "price_max": 2100.0,
                "price_label": "₹1,750/night",
                "amenities": ["Free WiFi", "Breakfast", "Secure Parking"],
                "source": "osm",
                "is_selected": True,
                "detour_km": 0.0,
            },
            {
                "checkpoint_id": "cp-03",
                "category": "stay",
                "name": "Hotel Abode Banjara",
                "address": "Banjara Hills, Hyderabad",
                "lat": 17.4126,
                "lng": 78.4483,
                "description": "Premium mid-range business hotel near arterial bypass",
                "rating": 4.2,
                "review_count": 230,
                "price_min": 1800.0,
                "price_max": 2200.0,
                "price_label": "₹1,800/night",
                "amenities": ["Free WiFi", "AC", "Secure Parking"],
                "source": "osm",
                "is_selected": True,
                "detour_km": 1.2,
            },
            {
                "checkpoint_id": "cp-04",
                "category": "stay",
                "name": "Tuli Imperial",
                "address": "Ramdaspeth, Nagpur",
                "lat": 21.135,
                "lng": 79.075,
                "description": "Central overnight hub with EV charging point",
                "rating": 4.1,
                "review_count": 540,
                "price_min": 2200.0,
                "price_max": 2600.0,
                "price_label": "₹2,200/night",
                "amenities": ["Free WiFi", "AC", "EV Charging Point"],
                "source": "osm",
                "is_selected": True,
                "detour_km": 0.8,
            },
            {
                "checkpoint_id": "cp-07",
                "category": "stay",
                "name": "Himalayan River Resort",
                "address": "Old Manali, Himachal Pradesh",
                "lat": 32.245,
                "lng": 77.185,
                "description": "Heated mountain rooms essential for high altitude acclimatisation",
                "rating": 4.6,
                "review_count": 890,
                "price_min": 2800.0,
                "price_max": 3400.0,
                "price_label": "₹2,800/night",
                "amenities": ["Mountain View", "Heater", "Free Parking"],
                "source": "osm",
                "is_selected": True,
                "detour_km": 1.5,
            },
            # ── Food & Restaurants ──
            {
                "checkpoint_id": "cp-02",
                "category": "restaurant",
                "name": "Crossroads Andhra Mess",
                "address": "Governorpet, Vijayawada",
                "lat": 16.51,
                "lng": 80.63,
                "description": "Authentic spicy Andhra thali, Gongura pachadi & curd rice",
                "rating": 4.5,
                "review_count": 1420,
                "price_min": 250.0,
                "price_max": 400.0,
                "price_label": "₹250–400 per person",
                "amenities": ["Pure Vegetarian", "Unlimited Thali"],
                "opening_hours": "11:30–22:30",
                "source": "osm",
                "is_selected": True,
                "detour_km": 0.0,
            },
            {
                "checkpoint_id": "cp-03",
                "category": "restaurant",
                "name": "Bawarchi Restaurant",
                "address": "RTC Cross Roads, Hyderabad",
                "lat": 17.4062,
                "lng": 78.4691,
                "description": "Renowned Hyderabadi Dum Biryani and Mirchi Ka Salan",
                "rating": 4.4,
                "review_count": 25000,
                "price_min": 350.0,
                "price_max": 500.0,
                "price_label": "₹350–500 per person",
                "amenities": ["Vegetarian options", "Family Hall"],
                "opening_hours": "12:00–23:00",
                "source": "osm",
                "is_selected": True,
                "detour_km": 0.5,
            },
            {
                "checkpoint_id": "cp-06",
                "category": "restaurant",
                "name": "Murthal Haveli Dhaba",
                "address": "GT Road / NH-44, Murthal",
                "lat": 29.02,
                "lng": 77.07,
                "description": "Highway parathas with white makkhan & sweet lassi on NH-44",
                "rating": 4.6,
                "review_count": 8500,
                "price_min": 250.0,
                "price_max": 450.0,
                "price_label": "₹250–450 per person",
                "amenities": ["24x7 Open", "Huge Parking", "Clean Restrooms"],
                "opening_hours": "24 Hours",
                "source": "osm",
                "is_selected": True,
                "detour_km": 0.0,
            },
            # ── Attractions ──
            {
                "checkpoint_id": "cp-02",
                "category": "attraction",
                "name": "Kanaka Durga Temple",
                "address": "Indrakeeladri Hill, Vijayawada",
                "lat": 16.515,
                "lng": 80.605,
                "description": "Historic hill temple with panoramic views of River Krishna",
                "rating": 4.7,
                "review_count": 24000,
                "price_min": 0.0,
                "price_max": 100.0,
                "price_label": "Free entry",
                "amenities": ["Panoramic View", "Historic Site"],
                "source": "osm",
                "is_selected": True,
                "detour_km": 0.5,
                "estimated_visit_min": 90,
                "entry_price_inr": 0.0,
            },
            {
                "checkpoint_id": "cp-03",
                "category": "attraction",
                "name": "Golconda Fort",
                "address": "Golconda, Hyderabad",
                "lat": 17.3833,
                "lng": 78.4011,
                "description": "Medieval fortress with acoustic architecture and diamond vaults",
                "rating": 4.4,
                "review_count": 14200,
                "price_min": 25.0,
                "price_max": 25.0,
                "price_label": "₹25 entry",
                "amenities": ["Heritage Site", "Guided Tours"],
                "source": "osm",
                "is_selected": True,
                "detour_km": 2.5,
                "estimated_visit_min": 120,
                "entry_price_inr": 25.0,
            },
            {
                "checkpoint_id": "cp-07",
                "category": "attraction",
                "name": "Solang Valley & Atal Tunnel",
                "address": "Solang, Manali",
                "lat": 32.315,
                "lng": 77.155,
                "description": "Alpine meadow and entrance to world's longest high-altitude highway tunnel",
                "rating": 4.8,
                "review_count": 18500,
                "price_min": 0.0,
                "price_max": 0.0,
                "price_label": "Free entry",
                "amenities": ["Snow Views", "Engineering Marvel"],
                "source": "osm",
                "is_selected": True,
                "detour_km": 0.0,
                "estimated_visit_min": 150,
                "entry_price_inr": 0.0,
            },
        ]

        if checkpoint_id:
            places = [p for p in places if p["checkpoint_id"] == checkpoint_id]
        if category:
            places = [p for p in places if p["category"] == category]
        return places
