/**
 * Locations data access — field names mirror `backend/app/schemas/resources.py`
 * (`LocationIn`/`LocationOut`) and `backend/app/api/v1/resources.py` (`locations`).
 *
 * CRUD operations generated by `build_crud_router`:
 * - GET "" (returns Page<Location>)
 * - POST "" (201)
 * - GET "/{id}"
 * - PUT "/{id}" (update whole record)
 * - DELETE "/{id}" (204)
 */
import { apiRequest, ApiError } from "./client";

export type LocationType = "depot" | "stop" | "warehouse";

export interface Location {
  id: string;
  created_at: string;
  updated_at: string;
  name: string;
  address: string | null;
  latitude: number;
  longitude: number;
  type: LocationType;
  zone: string | null;
  notes: string | null;
}

export type LocationInput = Omit<Location, "id" | "created_at" | "updated_at">;

export interface Page<T> {
  items: T[];
  total: number;
  limit: number;
  offset: number;
}

export interface ListLocationsParams {
  q?: string;
  type?: LocationType;
  zone?: string;
  sort?: string;
  order?: "asc" | "desc";
  limit?: number;
  offset?: number;
  signal?: AbortSignal;
}

export const LOCATION_TYPE_LABELS: Record<LocationType, string> = {
  depot: "Depot",
  stop: "Stop",
  warehouse: "Warehouse",
};

export async function listLocations(params: ListLocationsParams = {}): Promise<Page<Location>> {
  const { signal, ...query } = params;
  return apiRequest<Page<Location>>("/locations", {
    query: { limit: 50, offset: 0, sort: "name", order: "asc", ...query },
    signal,
  });
}

export async function getLocation(id: string, signal?: AbortSignal): Promise<Location> {
  return apiRequest<Location>(`/locations/${encodeURIComponent(id)}`, { signal });
}

/** Explicit allow-list for Location payload. */
export function toLocationPayload(l: LocationInput): Record<string, unknown> {
  return {
    name: l.name.trim(),
    address: l.address ? l.address.trim() : null,
    latitude: l.latitude,
    longitude: l.longitude,
    type: l.type,
    zone: l.zone ? l.zone.trim() : null,
    notes: l.notes ? l.notes.trim() : null,
  };
}

export async function createLocation(input: LocationInput): Promise<Location> {
  return apiRequest<Location>("/locations", {
    method: "POST",
    body: toLocationPayload(input),
  });
}

export async function updateLocation(id: string, input: LocationInput): Promise<Location> {
  return apiRequest<Location>(`/locations/${encodeURIComponent(id)}`, {
    method: "PUT",
    body: toLocationPayload(input),
  });
}

export async function deleteLocation(id: string): Promise<void> {
  await apiRequest<unknown>(`/locations/${encodeURIComponent(id)}`, {
    method: "DELETE",
  });
}

export { ApiError };
