"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-09 16:44:29.408687
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('latitude BETWEEN -90 AND 90', name='ck_locations_lat'),
    sa.CheckConstraint('longitude BETWEEN -180 AND 180', name='ck_locations_lng'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_locations_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_locations_ws_name', ['workspace_id', 'name'], unique=False)
        batch_op.create_index('ix_locations_ws_type', ['workspace_id', 'type'], unique=False)

    op.create_table('scenarios',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenarios_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_scenarios_ws_name', ['workspace_id', 'name'], unique=False)

    op.create_table('settings',
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workspace_id', 'key')
    )
    op.create_table('vehicle_profiles',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('payload_kg', sa.Float(), nullable=False),
    sa.Column('volume_m3', sa.Float(), nullable=False),
    sa.Column('energy_type', sa.String(length=20), nullable=False),
    sa.Column('efficiency_value', sa.Float(), nullable=False),
    sa.Column('efficiency_unit', sa.String(length=20), nullable=False),
    sa.Column('energy_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fixed_cost_per_delivery', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('operating_cost_per_km', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('avg_speed_kmph', sa.Float(), nullable=False),
    sa.Column('emissions_g_per_km', sa.Float(), nullable=False),
    sa.Column('range_km', sa.Float(), nullable=True),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('verification', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('efficiency_value > 0', name='ck_vehicles_efficiency'),
    sa.CheckConstraint('payload_kg > 0', name='ck_vehicles_payload'),
    sa.CheckConstraint('volume_m3 > 0', name='ck_vehicles_volume'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_profiles_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_vehicles_ws_available', ['workspace_id', 'available'], unique=False)
        batch_op.create_index('ix_vehicles_ws_energy', ['workspace_id', 'energy_type'], unique=False)

    op.create_table('delivery_plans',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('depot_location_id', sa.String(length=36), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_distance_km', sa.Float(), nullable=True),
    sa.Column('total_duration_min', sa.Float(), nullable=True),
    sa.Column('total_cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_emissions_g', sa.Float(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['depot_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_plans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_plans_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_plans_ws_status', ['workspace_id', 'status'], unique=False)

    op.create_table('packages',
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('recipient', sa.String(length=200), nullable=True),
    sa.Column('location_id', sa.String(length=36), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('length_cm', sa.Float(), nullable=True),
    sa.Column('width_cm', sa.Float(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('volume_m3', sa.Float(), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('handling', sa.JSON(), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('service_minutes', sa.Float(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('weight_kg >= 0', name='ck_packages_weight'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_packages_location_id'), ['location_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_packages_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_packages_ws_deadline', ['workspace_id', 'deadline'], unique=False)
        batch_op.create_index('ix_packages_ws_reference', ['workspace_id', 'reference'], unique=False)
        batch_op.create_index('ix_packages_ws_status', ['workspace_id', 'status'], unique=False)

    op.create_table('delivery_events',
    sa.Column('plan_id', sa.String(length=36), nullable=True),
    sa.Column('package_id', sa.String(length=36), nullable=True),
    sa.Column('vehicle_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['delivery_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_events_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_events_plan', ['plan_id'], unique=False)
        batch_op.create_index('ix_events_ws_time', ['workspace_id', 'occurred_at'], unique=False)

    op.create_table('optimization_runs',
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=True),
    sa.Column('request', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('runtime_ms', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['delivery_plans.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('optimization_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_optimization_runs_workspace_id'), ['workspace_id'], unique=False)
        batch_op.create_index('ix_runs_ws_kind_status', ['workspace_id', 'kind', 'status'], unique=False)

    op.create_table('plan_assignments',
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('vehicle_id', sa.String(length=36), nullable=False),
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('eta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['delivery_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'package_id', name='uq_assignment_plan_package')
    )
    with op.batch_alter_table('plan_assignments', schema=None) as batch_op:
        batch_op.create_index('ix_assignments_plan_vehicle', ['plan_id', 'vehicle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plan_assignments_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plan_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plan_assignments_workspace_id'))
        batch_op.drop_index('ix_assignments_plan_vehicle')

    op.drop_table('plan_assignments')
    with op.batch_alter_table('optimization_runs', schema=None) as batch_op:
        batch_op.drop_index('ix_runs_ws_kind_status')
        batch_op.drop_index(batch_op.f('ix_optimization_runs_workspace_id'))

    op.drop_table('optimization_runs')
    with op.batch_alter_table('delivery_events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_ws_time')
        batch_op.drop_index('ix_events_plan')
        batch_op.drop_index(batch_op.f('ix_delivery_events_workspace_id'))

    op.drop_table('delivery_events')
    with op.batch_alter_table('packages', schema=None) as batch_op:
        batch_op.drop_index('ix_packages_ws_status')
        batch_op.drop_index('ix_packages_ws_reference')
        batch_op.drop_index('ix_packages_ws_deadline')
        batch_op.drop_index(batch_op.f('ix_packages_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_packages_location_id'))

    op.drop_table('packages')
    with op.batch_alter_table('delivery_plans', schema=None) as batch_op:
        batch_op.drop_index('ix_plans_ws_status')
        batch_op.drop_index(batch_op.f('ix_delivery_plans_workspace_id'))

    op.drop_table('delivery_plans')
    with op.batch_alter_table('vehicle_profiles', schema=None) as batch_op:
        batch_op.drop_index('ix_vehicles_ws_energy')
        batch_op.drop_index('ix_vehicles_ws_available')
        batch_op.drop_index(batch_op.f('ix_vehicle_profiles_workspace_id'))

    op.drop_table('vehicle_profiles')
    op.drop_table('settings')
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_index('ix_scenarios_ws_name')
        batch_op.drop_index(batch_op.f('ix_scenarios_workspace_id'))

    op.drop_table('scenarios')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index('ix_locations_ws_type')
        batch_op.drop_index('ix_locations_ws_name')
        batch_op.drop_index(batch_op.f('ix_locations_workspace_id'))

    op.drop_table('locations')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
